# Generated by Django 4.2.7 on 2023-11-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_notes_user_id_alter_notes_price_alter_notes_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='user_id',
            new_name='user',
        ),
    ]
