# Generated by Django 4.2.7 on 2023-11-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['id', 'user_id', 'sort', 'reason', 'price', 'date_time'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['f_name', 'l_name'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользоваетли'},
        ),
        migrations.AddField(
            model_name='note',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
